/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module customCounter_13 (
    input clk,
    input rst,
    input [25:0] amount,
    input resetCd,
    output reg ans
  );
  
  
  
  reg [25:0] M_ctr_d, M_ctr_q = 1'h0;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    if (resetCd == 1'h1) begin
      M_ctr_d = 1'h0;
    end
    if (M_ctr_q < amount) begin
      M_ctr_d = M_ctr_q + 1'h1;
    end
    ans = (M_ctr_q == amount) ? 1'h1 : 1'h0;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
